# **📊 Projeto Final: Análise de Dados Educacionais**

## **Bem-vindo ao Projeto Final do Curso de Python da FEA.dev!** 🎉

Chegou a hora de colocar em prática tudo o que você aprendeu no curso! Neste desafio, você vai explorar e analisar um conjunto de dados sobre o desempenho acadêmico de estudantes. Seu objetivo será realizar uma análise exploratória completa e responder a uma pergunta norteadora, gerando insights a partir dos dados.

---

## **🚀 O Desafio**

### **Pergunta Norteadora**:  
**"Quais fatores demográficos, acadêmicos e comportamentais mais influenciam a classificação e a média de notas dos estudantes?"**

As variáveis de interesse são **`Classificacao_Notas` e `Media_Notas`**. Investigue como elas se relaciona com outros fatores, como idade, gênero, faltas, horas de estudo e participação em atividades extracurriculares. 📝

---

## **📌 Etapas do Desafio**

1. **Importação e Exploração dos Dados**:
   - Leia o dataset e obtenha uma visão geral das informações.
   - Verifique o formato dos dados, tipos de variáveis e valores ausentes ou duplicados.

2. **Preparação e Limpeza**:
   - Renomeie colunas, trate valores ausentes e ajuste os dados conforme necessário.
   - Crie novas colunas, se útil para a análise ou visualização.

3. **Análise Exploratória**:
   - Investigue a relação entre **`Classificacao_Notas` e `Media_Notas`** com outras variáveis.
   - Exemplos de perguntas a explorar:
     - Alunos que participam de atividades extracurriculares têm melhor desempenho?
     - O número de faltas impacta a classificação?
     - Há diferenças de desempenho por idade, gênero ou etnia?

4. **Visualização de Dados**:
   - Crie gráficos (ex.: histogramas, boxplots, scatter plots) para apresentar os padrões encontrados de forma clara e visualmente atraente. 📈

5. **Conclusões**:
   - Resuma os principais insights.
   - Destaque os fatores mais relevantes que influenciam as classificações e as médias de notas.

---

## **📋 Regras e Diretrizes**
- Este desafio é focado em análise exploratória e visualização de dados.
- Documente seu processo com comentários no código.
- Seja criativo nas análises e visualizações! 🖌️

---

## **Dica Extra:**

Use documentações, tutoriais e até pesquisas na internet para te ajudar, mas lembre-se: é essencial entender e refletir sobre o que está aplicando. 🚫 Evite usar o GPT sem raciocinar!

---

## **🎯 Objetivos de Aprendizado**
- Reforçar os conceitos aprendidos ao longo do curso.  
- Manipular dados com **`pandas`** e **`numpy`**.  
- Criar visualizações com **`matplotlib`** e **`seaborn`**.  
- Desenvolver uma abordagem crítica para interpretar padrões em dados.  

---

## **📝 Como entregar o Projeto Final**

### Passo a Passo:
1. **Prepare seu notebook**:
   - Certifique-se de que ele está completo, organizado e com comentários explicando seu processo.
2. **Envie apenas esse arquivo ipynb!**:
   - Acesse o formulário oficial: **[Link do Formulário](https://forms.gle/oDvYmwKfxscKbMaF8)**.
   - Anexe o arquivo do seu notebook na aba "Projeto Final" e **NÃO arquive o dataset, `dados_estudantes.csv`, utilizado!**
   - Este é o mesmo formulário utilizado para as listas de exercícios. Envie tudo junto para garantir o registro correto.

### **Prazos e Certificação**:
- **Prazo de entrega**: Aumentamos para dia **15/12** (23h59).  
- **Certificação**: Se você completar pelo menos **70% das listas e o projeto final**, receberá um certificado oficial de conclusão. 🎓  

---

## **🎁 Benefícios Extras para Alunos USP**  
Se você é aluno(a) da USP, terá a oportunidade de participar do nosso **Processo Seletivo** para integrar a equipe da FEA.dev! Após a entrega do projeto final, fique de olho no seu e-mail para mais informações.  

---

## **📚 Origem dos Dados**
Este dataset foi disponibilizado por Rabie El Kharoua no Kaggle e está licenciado sob CC BY 4.0:  

> El Kharoua, R. (2024). Students Performance Dataset.  
> Disponível em: [Kaggle Dataset Link](https://www.kaggle.com/datasets/rabieelkharoua/students-performance-dataset).

---

## **💡 PS: Você Chegou Até Aqui!**

Estamos **muito orgulhosos** de ver o quanto você evoluiu ao longo do curso! 💪  
Este projeto é a chance perfeita de consolidar tudo o que aprendeu e mostrar do que é capaz.  

Lembre-se: a jornada no mundo da programação é cheia de descobertas, desafios e até frustrações (Sabemos bem como é kkk), mas cada linha de código escrita é um passo a mais rumo ao seu sucesso. Não pare por aqui! Continue explorando, aprendendo e se desafiando. O **infinito** é o seu limite.

Parabéns por ter chegado até aqui! 🎉 Estamos torcendo por você e muito animados para ver o seu projeto final. Vamos juntos nessa jornada incrível! 🧑‍💻

🎯 **Agora é com você! Explore, analise e descubra os padrões escondidos nos dados. Boa sorte!** 🍀

---

## **📊 Descrição das Colunas do DataFrame**

### **Identificação do Estudante**  
- **ID_Aluno**: Identificador único para cada aluno (de 1001 a 3392).

### **👥 Detalhes Demográficos**  
- **Idade**: Idade dos estudantes, variando de 15 a 18 anos.  
- **Genero**: Gênero do estudante:
  - 0: Masculino
  - 1: Feminino  
- **Etnia**: Etnia dos estudantes:
  - 0: Caucasiano
  - 1: Afrodescendente
  - 2: Asiático
  - 3: Outra

### **👨‍👩‍👧 Educação dos Pais**  
- **Escolaridade_Pais**: Nível de escolaridade dos pais:
  - 0: Nenhum
  - 1: Ensino Médio
  - 2: Alguma Faculdade
  - 3: Graduação
  - 4: Pós-Graduação ou Superior

### **📚 Hábitos de Estudo**  
- **Horas_Estudo_Semanais**: Tempo de estudo semanal em horas (0 a 20).  
- **Faltas**: Número de faltas no ano letivo (0 a 30).  
- **Aulas_Particulares**: Participação em aulas particulares:
  - 0: Não
  - 1: Sim

### **👨‍👩‍👧 Envolvimento Parental**  
- **Apoio_Pais**: Nível de apoio dos pais:
  - 0: Nenhum
  - 1: Baixo
  - 2: Moderado
  - 3: Alto
  - 4: Muito Alto

### **🏫 Atividades Extracurriculares**  
- **Atividades_Extracurriculares**: Participação em atividades extracurriculares:
  - 0: Não
  - 1: Sim  
- **Esportes**: Participação em esportes:
  - 0: Não
  - 1: Sim  
- **Musica**: Participação em atividades musicais:
  - 0: Não
  - 1: Sim  
- **Voluntariado**: Participação em atividades de voluntariado:
  - 0: Não
  - 1: Sim

### **📈 Desempenho Acadêmico**  
- **Media_Notas**: Média das notas (GPA), variando de 2.0 a 4.0.  
- **Classificacao_Notas**: Classificação do aluno com base na média das notas:
  - 0: 'A' (Média >= 3.5)
  - 1: 'B' (3.0 <= Média < 3.5)
  - 2: 'C' (2.5 <= Média < 3.0)
  - 3: 'D' (2.0 <= Média < 2.5)
  - 4: 'F' (Média < 2.0)

---

In [34]:
# Importando as bibliotecas estudadas durante o curso
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importando o dataset

# Verificando as primeiras linhas do dataset

In [35]:
traducao_colunas = {
    "StudentID": "ID_Aluno",
    "Age": "Idade",
    "Gender": "Genero",
    "Ethnicity": "Etnia",
    "ParentalEducation": "Escolaridade_Pais",
    "StudyTimeWeekly": "Horas_Estudo_Semanais",
    "Absences": "Faltas",
    "Tutoring": "Aulas_Particulares",
    "ParentalSupport": "Apoio_Pais",
    "Extracurricular": "Atividades_Extracurriculares",
    "Sports": "Esportes",
    "Music": "Musica",
    "Volunteering": "Voluntariado",
    "GPA": "Media_Notas",
    "GradeClass": "Classificacao_Notas"
}

# Renomear as colunas

In [36]:
# Agora está por conta própria e pronto para brilhar! 🌟

### 🔍 **Pergunta Norteadora** ###
# Quais fatores demográficos, acadêmicos e comportamentais mais influenciam a classificação e a média de notas dos estudantes?

# 🛠️ **Dicas para começar:**
# - Dê uma boa olhada no dataset.
# - Explore as relações entre a variável `Classificacao_Notas` e outros fatores, como gênero, horas de estudo, faltas, etc.
# - Use gráficos e tabelas para visualizar os padrões encontrados.
# - Escreva suas reflexões e hipóteses sobre o que você encontrou.
# - E o mais importante: divirta-se no processo de análise! 😄

# Não há limite para o número de células ou análises. O espaço é todo seu! 🚀

# **SEU CÓDIGO COMEÇA AQUI** 👇

In [48]:
### visao geral do dataset ###

dt = pd.read_csv('../data/dados_estudantes.csv', sep = ',')
dt = dt.rename(traducao_colunas, axis = 1) # traduzir nome das colunas

dt.info()
dt

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID_Aluno                      2392 non-null   int64
 1   Idade                         2392 non-null   int64
 2   Genero                        2392 non-null   int64
 3   Etnia                         2392 non-null   int64
 4   Escolaridade_Pais             2392 non-null   int64
 5   Horas_Estudo_Semanais         2392 non-null   float64
 6   Faltas                        2392 non-null   int64
 7   Aulas_Particulares            2392 non-null   int64
 8   Apoio_Pais                    2392 non-null   int64
 9   Atividades_Extracurriculares  2392 non-null   int64
 10  Esportes                      2392 non-null   int64
 11  Musica                        2392 non-null   int64
 12  Voluntariado                  2392 non-null   int64
 13  Media_Notas                   2392 non-null   float64
 14  Classificacao_Notas           2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

,ID_Aluno,Idade,Genero,Etnia,Escolaridade_Pais,Horas_Estudo_Semanais,Faltas,Aulas_Particulares,Apoio_Pais,Atividades_Extracurriculares,Esportes,Musica,Voluntariado,Media_Notas,Classificacao_Notas
0,1001,17,1,0,2,19.8,7,1,2,0,0,1,0,2.9,2.0
1,1002,18,0,0,1,15.4,0,0,1,0,0,0,0,3.0,1.0
2,1003,15,0,2,3,4.2,26,0,2,0,0,0,0,0.1,4.0
3,1004,17,1,0,3,10.0,14,0,3,1,0,0,0,2.1,3.0
4,1005,17,1,0,2,4.7,17,1,3,0,0,0,0,1.3,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.7,2,0,4,1,0,0,0,3.5,0.0
2388,3389,17,0,0,1,7.6,4,1,4,0,1,0,0,3.3,4.0
2389,3390,16,1,0,2,6.8,20,0,2,0,0,0,1,1.1,2.0
2390,3391,16,1,1,0,12.4,17,0,2,0,1,1,0,1.8,1.0
2391,3392,16,1,0,2,17.8,13,0,2,0,0,0,1,2.1,1.0

In [49]:
### limpeza e tratamento dos dados ###

pd.options.display.float_format = '{:.1f}'.format # definir visualizacao para numeros com uma casa decimal

dt.isnull().sum() # contagem de valores nulos
dt.duplicated().sum() # contagem de linhas duplicadas

# substituicao de valores das colunas
dt["Genero"] = dt.apply(
    lambda row: 'masculino' if row["Genero"] == 0
    else 'feminino',
    axis = 1
)

dt["Etnia"] = dt.apply(
    lambda row: 'caucasasiano' if row["Etnia"] == 0
    else 'afrodescendente' if row["Etnia"] == 1
    else 'asiatico' if row["Etnia"] == 2 
    else 'outro',
    axis = 1
)

dt["Escolaridade_Pais"] = dt.apply(
    lambda row: 'nenhuma' if row["Escolaridade_Pais"] == 0
    else 'ensino_medio' if row["Escolaridade_Pais"] == 1
    else 'graduacao_incompleta' if row["Escolaridade_Pais"] == 2
    else 'graduacao_completa' if row["Escolaridade_Pais"] == 3
    else 'pos_graduacao',
    axis = 1
)

dt["Aulas_Particulares"] = dt.apply(
    lambda row: 'nao' if row["Aulas_Particulares"] == 0
    else 'sim',
    axis = 1
)

dt["Apoio_Pais"] = dt.apply(
    lambda row: 'nenhum' if row["Apoio_Pais"] == 0
    else 'baixo' if row["Apoio_Pais"] == 1
    else 'moderado' if row["Apoio_Pais"] == 2
    else 'alto' if row["Apoio_Pais"] == 3
    else 'muito_alto',
    axis = 1
)

dt["Atividades_Extracurriculares"] = dt.apply(
    lambda row: 'nao' if row["Atividades_Extracurriculares"] == 0
    else 'sim',
    axis = 1
)

dt["Esportes"] = dt.apply(
    lambda row: 'nao' if row["Esportes"] == 0
    else 'sim',
    axis = 1
)

dt["Musica"] = dt.apply(
    lambda row: 'nao' if row["Musica"] == 0
    else 'sim',
    axis = 1
)

dt["Voluntariado"] = dt.apply(
    lambda row: 'nao' if row["Voluntariado"] == 0
    else 'sim',
    axis = 1
)

dt["Classificacao_Notas"] = dt.apply(
    lambda row: 'A' if row["Classificacao_Notas"] == 0
    else 'B' if row["Classificacao_Notas"] == 1
    else 'C' if row["Classificacao_Notas"] == 2
    else 'D' if row["Classificacao_Notas"] == 3
    else 'F',
    axis = 1
)

dt

,ID_Aluno,Idade,Genero,Etnia,Escolaridade_Pais,Horas_Estudo_Semanais,Faltas,Aulas_Particulares,Apoio_Pais,Atividades_Extracurriculares,Esportes,Musica,Voluntariado,Media_Notas,Classificacao_Notas
0,1001,17,feminino,caucasasiano,graduacao_incompleta,19.8,7,sim,moderado,nao,nao,sim,nao,2.9,C
1,1002,18,masculino,caucasasiano,ensino_medio,15.4,0,nao,baixo,nao,nao,nao,nao,3.0,B
2,1003,15,masculino,asiatico,graduacao_completa,4.2,26,nao,moderado,nao,nao,nao,nao,0.1,F
3,1004,17,feminino,caucasasiano,graduacao_completa,10.0,14,nao,alto,sim,nao,nao,nao,2.1,D
4,1005,17,feminino,caucasasiano,graduacao_incompleta,4.7,17,sim,alto,nao,nao,nao,nao,1.3,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,feminino,caucasasiano,graduacao_completa,10.7,2,nao,muito_alto,sim,nao,nao,nao,3.5,A
2388,3389,17,masculino,caucasasiano,ensino_medio,7.6,4,sim,muito_alto,nao,sim,nao,nao,3.3,F
2389,3390,16,feminino,caucasasiano,graduacao_incompleta,6.8,20,nao,moderado,nao,nao,nao,sim,1.1,C
2390,3391,16,feminino,afrodescendente,nenhuma,12.4,17,nao,moderado,nao,sim,sim,nao,1.8,B
2391,3392,16,feminino,caucasasiano,graduacao_incompleta,17.8,13,nao,moderado,nao,nao,nao,sim,2.1,B

In [ ]:
### organizacao de colunas do dataset ###

# adicao das colunas 'esportes', 'musica' e 'voluntariado' em 'atividades extracurriculares'
dt["Atividades_Extracurriculares"] = dt.apply(
    lambda x: 'sim' if x["Atividades_Extracurriculares"] == 'sim' 
    or 'sim' in x[["Esportes", "Musica", "Voluntariado"]].values 
    else 'nao',
    axis = 1
)

# excluir as colunas 'esportes', 'musica' e 'voluntariado'
dt = dt.drop(columns=["Esportes", "Musica", "Voluntariado"])

dt

,ID_Aluno,Idade,Genero,Etnia,Escolaridade_Pais,Horas_Estudo_Semanais,Faltas,Aulas_Particulares,Apoio_Pais,Atividades_Extracurriculares,Media_Notas,Classificacao_Notas
0,1001,17,feminino,caucasasiano,graduacao_incompleta,19.8,7,sim,moderado,sim,2.9,C
1,1002,18,masculino,caucasasiano,ensino_medio,15.4,0,nao,baixo,nao,3.0,B
2,1003,15,masculino,asiatico,graduacao_completa,4.2,26,nao,moderado,nao,0.1,F
3,1004,17,feminino,caucasasiano,graduacao_completa,10.0,14,nao,alto,sim,2.1,D
4,1005,17,feminino,caucasasiano,graduacao_incompleta,4.7,17,sim,alto,nao,1.3,F
...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,feminino,caucasasiano,graduacao_completa,10.7,2,nao,muito_alto,sim,3.5,A
2388,3389,17,masculino,caucasasiano,ensino_medio,7.6,4,sim,muito_alto,sim,3.3,F
2389,3390,16,feminino,caucasasiano,graduacao_incompleta,6.8,20,nao,moderado,sim,1.1,C
2390,3391,16,feminino,afrodescendente,nenhuma,12.4,17,nao,moderado,sim,1.8,B
2391,3392,16,feminino,caucasasiano,graduacao_incompleta,17.8,13,nao,moderado,sim,2.1,B